### PR TITLE
Implement labels in Set clause

### LINKED ISSUE #46: Support labels in Set clause
Similar to the support just added in Remove.  Allows for renaming of labels for example:

`MATCH (n:oldLabel) SET n :newLabel REMOVE n:oldLabel`

I will work on this when I get some time and submit a PR.  This issue is so I don't lose track of it.

### PR DESCRIPTION
**Pull request by wgorder**
Added the ability to set labels in a set clause.
Added supporting test cases.
Cleaned up some code duplication in Identifier.java

closes #46

### CODE REVIEW

**Comment by wgorder** [comment]
@jexp  Can you have a look at this one?

**Comment by wgorder** [comment]
@jexp  Do you happen to have a copy of the neotechnology formatter you can add to this project?  It is a bit painful staying consistent with the formatting, as it a bit different then the formatters I use.  I use IntelliJ if that matters.

**Comment by wgorder** [comment]
pinging @jexp  just wanna make sure you saw this.

**Comment by jexp** [comment]
Hey @wgorder here it is: https://dl.dropboxusercontent.com/u/14493611/neo4j-intellij.jar

**Comment by wgorder** [comment]
@jexp  Thank you sir!

**Pull request merged**
