### PR TITLE
support includes and not_includes filter

### PR DESCRIPTION
**Pull request by AakashSorathiya**

### CODE REVIEW

**Comment by michael-simons** [comment]
Hi Aakash,

thanks for your effort. I am not against having that feature, but there a couple of things to discuss

- The `not` is redundant, that can be achieved with just negating the condition
- There seem to be no tests
- I would prefer sub tree that does not require changes to the string literal

**Comment by AakashSorathiya** [comment]
Hi Michael, sorry for delay. I am busy with some other commitments so give me some more time I will make the changes according the points that you have mentioned. Thanks!

**Comment by AakashSorathiya** [comment]
Hi Michael, I have made changes as you suggested. Please let me know if any further polishing is required. Thanks!

**Comment by michael-simons** [comment]
Hi @AakashSorathiya 

I took your code and your intention and reworked it a bit so that it fits the goal of our project here.
The only difference here is that I switched the meaning of lhs/rhs.

So now it reads `lhs.includesAll(rhs)`. 

I hope that it is ok, it just feels more in line how things have been don in this project so far. Sorry if this is probably different in your (spoken) language.

Thanks for your contribution, will merge soon.

**Pull request merged**
