### PR TITLE
Provide a function to bind values to a parameter and collect all bound parameter values

### LINKED ISSUE #135: Provide a function to bind values to a parameter and collect all bound parameter values
Allows to bind values to parameters so that you can use them as follows:

```java
Statement statement = Cypher
            .match(userNode)
            .returning(userNode)
            .limit(Cypher.parameter("param").withValue(5)).build();

Map<String, Object> usedParams = ParameterValueCollector.collectBoundParameters(statement);
```

### PR DESCRIPTION
**Pull request by Andy2003**
resolves #135

### CODE REVIEW

**Comment by michael-simons** [comment]
I'm inclined to add convenience methods 

* `getParameter()`
* `toCypher()`

to the `Statement` class to avoid going through the collector (and for completeness, through the default renderer).

WDYT?

**Comment by meistermeier** [comment]
Could you elaborate on 
> to avoid going through the collector 
From my understanding each visitor is separated and needs to get called explicitly.
Even though I think that the convenience methods would make sense I won't give the `Statement` more functionality in itself but just keep it as a subject that gets passed over to the parameter and/or render visitor.

**Comment by Andy2003** [comment]
> I'm inclined to add convenience methods
> 
> * `getParameter()`
> * `toCypher()`
> 
> to the `Statement` class to avoid going through the collector (and for completeness, through the default renderer).
> 
> WDYT?

@michael-simons I agree with the suggestion, but also don't have much pain with the current way of doing things. I am also planning a PR with a pretty-print renderer, so the convenience method would be out of the question for us.

**Comment by michael-simons** [comment]
Thanks for your input.

The parameters are a closed use case, keeping it close to the statement makes it possible to reduce the API on the Parameter.

For the renderer, that should be possible in both ways.

**Pull request merged**
