### PR TITLE
Allow extending RenderingVisitor to customize rendering

### LINKED ISSUE #144: Allow extending RenderingVisitor to customize rendering
Please make the `RenderingVisitor` public and extendable, so we can customize the rendering

### PR DESCRIPTION
**Pull request by Andy2003**
resolves #144

### CODE REVIEW

**Comment by michael-simons** [comment]
I would rather suggest copy the whole thing and run your own. This very much intended to be this way.

**Comment by meistermeier** [comment]
I am completely with Michael: There should be a very focused responsibility for each visitor implementation.
The `RenderingVisitor` is for example the "technical" render component. In contrast there should be a `PrettyPrintVisitor` or similar which purpose is to create a (more) human readable representation of the `Statement`.
Yes, there might be a lot of overlaps but in general the clean separation helps to keep the visitors themself focused and not feature bloated.

**Comment by michael-simons** [comment]
With regard to maintenance burden: I would rather maintain a custom renderer or a flag on the existing implementation, than making it public and thus be obligated to evolve in a compilable fashion.

For a pretty prenting renderer in the same package things would already work: The class is not final, and neither are the methods. I would not mind making fields protected to be accessible by inheritors.

**Comment by Andy2003** [comment]
close this in favor of #147

**Pull request closed without merging**
