### PR TITLE
Add support for ON MATCH and ON CREATE

### PR DESCRIPTION
**Pull request by wgorder**
Added support for ON MATCH and ON CREATE which can follow a merge clause.  Added some
supporting test cases.

### CODE REVIEW

**Comment by wgorder** [comment]
@jexp  Hey I had need for this so thought I would give it back.  If you have a formatter you use for Intellij let me know. Every time I try to leave things alone it just kind of takes over :)

If you can let me know when the next release is, and I will stop using my custom build.

**Comment by jexp** [comment]
Looks good to me, but your IDE setup did a lot of unrelated changes to imports and whitespace? Would you mind limiting the PR to the actual code change? Thanks a ton.

**Comment by wgorder** [comment]
@jexp  Look again.  I just did it in Sublime.  Intellij seems to have a mind of its own when it comes to that.  I am sure there are 20 settings I would have to tweak hidden somewhere. :)

**Comment by jexp** [comment]
Thanks a lot, Merged Manually.

**Comment by AdrianBesleaga** [comment]
@michael-simons I know this is very old but I was looking for this in the last version and it looks like the code and the support for "ON MATCH" and "ON CREATE" is not available anymore. 
Is there any plan to bring it back? Or maybe is already there and I didn't see it? 
Thank you in advance.

**Comment by michael-simons** [comment]
Hi @AdrianBesleaga No, it is not there yet. Good point. Please track https://github.com/neo4j-contrib/cypher-dsl/issues/104

**Pull request closed without merging**
