### PR TITLE
Change parser license to The Apache Software License, Version 2.0 (same as Neo4j Javacc based parser).

### PR DESCRIPTION
**Pull request by michael-simons**

### CODE REVIEW

**Comment by michael-simons** [comment]
Please @hindog and @fbiville can you confirm you are ok with those changes?

@hindog You contributed this feature in 2022 to the parser module https://github.com/neo4j-contrib/cypher-dsl/commit/21af28b0397def8add6342f92f5911d548df24dc

@fbiville You added the parser callbacks https://github.com/neo4j-contrib/cypher-dsl/commit/a2c02edf6dfb3ec055d14481f375576265607fee

@Andy2003 Please confirm as well, you touched the parser while we added the single API entry point.

This makes a lot of things easier down the road and is sanctioned with Valerio Malenchino.

**Review by jexp — APPROVED** [review]
LGTM thanks a lot @michael-simons

**Comment by fbiville** [comment]
OK with the change.

**Comment by Andy2003** [comment]
I'm OK with the changes as well

**Comment by hindog** [comment]
I'm fine with the change as well.  Sorry for the late reply!

**Comment by michael-simons** [comment]
Thanks a lot to all of you, much appreciated! <3

**Comment by ikwattro** [comment]
OMG ! 🎉 Thanks again @michael-simons

**Pull request merged**
